### ISSUE TITLE
Changer les chemins relatifs du modèle

### ISSUE THREAD

**Issue by Renaud-D-Harreville** [dataforgoodfr/batch7_rse#11]
Lors de l'import du module [indexer](https://github.com/dataforgoodfr/batch7_rse/blob/master/webapp/polls/rse_model/rse_watch/indexer.py), on obtient cette erreur au moment de lancer le serveur django : 

```
  File "/home/renaud/projects/batch7_rse/webapp/polls/models.py", line 8, in <module>
    from polls.rse_model.rse_watch.indexer import nlp
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 112, in <module>
    nlp = load_weighted_vectorizer(Config, create_from_scratch=True)  # TODO: delete when in production.
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 92, in load_weighted_vectorizer
    nlp = initialize_weighted_vectorizer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 70, in initialize_weighted_vectorizer
    scorer = load_scorer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 59, in load_scorer
    scorer = initialize_scorer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 25, in initialize_scorer
    df = pd.read_csv(conf.parsed_sent_file, sep=";")
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File ../data/processed/DPEFs/dpef_paragraphs_sentences.csv does not exist: '../data/processed/DPEFs/dpef_paragraphs_sentences.csv'
Initialization from scratch. [force_creation is set to 'True']
Initializing weighted vectorizer.
Scorer not found and thus created (at address: ../data/model/vectorizer_component/words_scorer.pckl)
```
En effet, l'application web étant lancée depuis le dossier webapp, et les noms de fichiers étants relatifs au dossier webapp/polls/rse_model/rse_watch, et non pas au dossier webapp du projet, les fichiers ne peuvent pas être trouvés.

@CharlesGaydon  Je peux faire cette modification si tu le souhaites, dis moi juste si le fait de changer les chemins de `../data/...` vers `polls/rse_model/data/...` a une autre incidence que je ne connais pas ?

**Comment by Renaud-D-Harreville** [comment]
D'autre part, je t'invite à [regarder cette page ci](https://docs.python.org/fr/3/library/pathlib.html) :)

Tu verras qu'il existe un meilleur moyen pour gérer les noms de fichiers en python autrement que via des str ;) 
On peut même faire grâce à ça des concaténations intuitives comme : 
```
>>> p = Path('/etc')
>>> q = p / 'init.d' / 'reboot'
```
Avec ces objets tu peux faire beaucoup de choes (décrits dans la page de documentation en lien), tu verras ça change une vie :p

Voila voila ;)

**Comment by CharlesGaydon** [comment]
> Tu verras qu'il existe un meilleur moyen pour gérer les noms de fichiers en python autrement que via des str ;)

Je connais pathlib.Path, et je les utilise d'ailleurs dans la suite du code, lorsqu'il s'agit d'identifier tous les PDFs.
Je comptais changer ça à terme, et bien le moment est venu ! Je te laisse t'en charger, car tu sera en mesure de détecter les bugs éventuel lié au fait d'appeler l'indexer depuis django. Ca ne devrait pas avoir d'impact pour les appels des mains des scripts sinon :)

**Comment by CharlesGaydon** [comment]
Je tente comme ça : 
https://github.com/dataforgoodfr/batch7_rse/pull/15
Avec data déplacé, et le script conf.py à la racine de webapp, auxquel est ajouté __init__.py.
Les chemins dans conf.py sont relatif à /webapp/, donc lorsque manage.py est appelé les chemins devraient être bons. Par contre je dois trouver le moyen de lancer les scripts en faisant appel à webapp.conf. 
Rajouter le chemin de webapp sera peut-être une solution, je continue demain.

**Comment by CharlesGaydon** [comment]
La solution actuelle est la N°3 d'une [question similaire sur stack](https://stackoverflow.com/a/16786993/8086033).
Pour le développement et les tests des scripts et modèles, il faut lancer le script main en tant que module, depuis l'extérieur de webapp.
`python -m webapp.main`
Tous les chemins de la configuration considèrent maintenant que le working directory est webapp\.

**Comment by Renaud-D-Harreville** [comment]
Bon, je crois que j'ai perdu mon ancien message, je vais réussir à retrouver la motivation de tout ré ecrire, donc je vais faire bref : 
J'ai essayer de recréer un package correct en séparant le code des données. DOnc j'ai refait le fichier config en ajoutant un paramètre qui permet de définir le dossier source pour le modèle (webapp/data/model dans notre cas). 

J'en ai profiter pour faire une énumération pour la méthode de scoring.

Il a fallu ensuite (après quelques réglages) rajouter dynamiquement le package rse_watch dans django. C'est le fichier polls/__init__.py qui fait ça. Ce même fichier tente aussi de charger le modèle.

Mais la j'ai un souci que je n'arrive pas à comprendre et pour lequel j'aurais certainement besoin de ton aide : 

```
Loading weighted vectorizer.
An error occured while loading weighted vectorizer:
[E053] Could not read meta.json from /home/renaud/projects/batch7_rse/webapp/data/model/Model/meta.json
We recreate the model from scratch and save it.
Initializing weighted vectorizer.
Scorer not found and thus created (at address: /home/renaud/projects/batch7_rse/webapp/data/model/Model/vectorizer_component/words_scorer.pckl)
Loading weighted vectorizer.
An error occured while loading weighted vectorizer:
[E053] Could not read meta.json from /home/renaud/projects/batch7_rse/webapp/data/model/Model/meta.json
We recreate the model from scratch and save it.
Initializing weighted vectorizer.
Scorer not found and thus created (at address: /home/renaud/projects/batch7_rse/webapp/data/model/Model/vectorizer_component/words_scorer.pckl)
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 100, in load_weighted_vectorizer
    nlp = spacy.load(conf.model_dir)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/spacy/util.py", line 168, in load_model
    return load_model_from_path(name, **overrides)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/spacy/util.py", line 192, in load_model_from_path
    meta = get_model_meta(model_path)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/spacy/util.py", line 242, in get_model_meta
    raise IOError(Errors.E053.format(path=meta_path))
OSError: [E053] Could not read meta.json from /home/renaud/projects/batch7_rse/webapp/data/model/Model/meta.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 55, in load_scorer
    f = open(conf.scorer_pickle_file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/renaud/projects/batch7_rse/webapp/data/model/Model/vectorizer_component/words_scorer.pckl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/renaud/projects/batch7_rse/webapp/polls/__init__.py", line 13, in <module>
    nlp = load_weighted_vectorizer(conf.Config(model_directory))
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 109, in load_weighted_vectorizer
    nlp = initialize_weighted_vectorizer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 69, in initialize_weighted_vectorizer
    scorer = load_scorer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 58, in load_scorer
    scorer = initialize_scorer(conf)
  File "/home/renaud/projects/batch7_rse/webapp/polls/rse_model/rse_watch/indexer.py", line 24, in initialize_scorer
    df = pd.read_csv(conf.parsed_sent_file, sep=";")
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/renaud/.virtualenvs/batch7-rse/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /home/renaud/projects/batch7_rse/webapp/data/model/DPEFs/__parsed_dpefs__/dpef_sentences.csv does not exist: '/home/renaud/projects/batch7_rse/webapp/data/model/DPEFs/__parsed_dpefs__/dpef_sentences.csv'
Loading weighted vectorizer.
An error occured while loading weighted vectorizer:
[E053] Could not read meta.json from /home/renaud/projects/batch7_rse/webapp/data/model/Model/meta.json
We recreate the model from scratch and save it.
Initializing weighted vectorizer.
Scorer not found and thus created (at address: /home/renaud/projects/batch7_rse/webapp/data/model/Model/vectorizer_component/words_scorer.pckl)
```

**Comment by CharlesGaydon** [comment]
Corrigé dans https://github.com/dataforgoodfr/batch7_rse/commit/6cea5d96636c675b9aa684a4a0e5f3d741c9ce8c
